// Textos de marca centralizados. Al desplegar una instancia separada para
// otro cliente (ver README § "Nueva instancia para otro cliente"), este es
// el único archivo de texto que hace falta editar — los colores viven en
// tailwind.config.js y el logo/imágenes en public/.
export const NOMBRE_CORTO = "InspeccionAPP";
export const NOMBRE_EMPRESA = "EQS";
export const NOMBRE_LEGAL = "Ethical Quality Services";
export const NOMBRE_APP = `${NOMBRE_EMPRESA} ${NOMBRE_CORTO}`;
export const DESCRIPCION_APP = `Control de inspecciones de calidad — ${NOMBRE_LEGAL}`;
export const PIE_PDF = `Generado automáticamente por ${NOMBRE_EMPRESA} Control de Inspecciones`;
export const PIE_PDF_EN = `Automatically generated by ${NOMBRE_EMPRESA} Inspection Control`;

// Contacto para "Solicitar demo" en la página pública. WhatsApp en formato
// internacional sin signos (ej. 5218112345678). Si ambos quedan vacíos, la
// página solo ofrece "Iniciar sesión".
export const CONTACTO_WHATSAPP = process.env.NEXT_PUBLIC_CONTACTO_WHATSAPP ?? "";
export const CONTACTO_EMAIL = process.env.NEXT_PUBLIC_CONTACTO_EMAIL ?? "";

/** Nombre de la organización que emite un reporte (multi-empresa); por omisión, la de esta instalación. */
export type EmpresaEmisora = { nombre: string; nombreCorto: string };
export const EMPRESA_POR_OMISION: EmpresaEmisora = { nombre: NOMBRE_LEGAL, nombreCorto: NOMBRE_EMPRESA };
